// Copies ABIs from the Foundry build (../out) into src/abis as typed `as const` exports.
// Run `forge build` in the repo root first, then `npm run abis`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const contracts = [
  ['BactoryFactory', 'BactoryFactory.sol'],
  ['Market', 'Market.sol'],
  ['TreasuryModule', 'TreasuryModule.sol'],
  ['YieldVault', 'YieldVault.sol'],
  ['AgentGuard', 'AgentGuard.sol'],
  ['HoldStrategy', 'HoldStrategy.sol'],
];
for (const [name, file] of contracts) {
  const { abi } = JSON.parse(readFileSync(join(root, 'out', file, `${name}.json`), 'utf8'));
  const out = `// Generated by scripts/generate-abis.mjs from out/${file}/${name}.json. Do not edit.\nexport const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(root, 'sdk', 'src', 'abis', `${name}.ts`), out);
  console.log('wrote', name, abi.length, 'entries');
}
